/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 30, 2025 10:28
 * @component Body
 * @description The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 */

export default {
  title: "HTML5/Block Elements/Body",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onafterprint: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires after the associated document has started printing or the print preview has been closed.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onbeforeprint: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires before the associated document is printed or previewed for printing.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onbeforeunload: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires before the user navigates away from the page.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onhashchange: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the fragment identifier part of the URL changes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onlanguagechange: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the user changes the preferred language of the user interface.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onmessage: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when a message is received from a different browsing context (e.g., an iframe).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onmessageerror: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when an error occurs while receiving a message from a different browsing context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onoffline: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the browser goes offline.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ononline: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the browser goes online.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onpagehide: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the user navigates away from a page.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onpageshow: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the user navigates to a page.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onpopstate: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the user navigates through the history by clicking the browser\'s Back or Forward buttons.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onrejectionhandled: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when a Promise is rejected and the rejection is handled by a Promise handler (e.g., catch).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onstorage: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when a storage area (e.g., localStorage or sessionStorage) changes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onunhandledrejection: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when a Promise is rejected but there is no rejection handler (e.g., catch).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    onunload: {
      type: {
        name: "string",
        required: false
      },
      description: "Fires when the user is navigating away from the page (similar to onbeforeunload).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: (args) => {
    let el = document.createElement("body");
    el.innerHTML = args.text;

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    classProp: "Sample value",
    data: {},
    dir: "",
    draggable: false,
    hidden: false,
    id: "Sample value",
    lang: "Sample value",
    onafterprint: "Sample value",
    onbeforeprint: "Sample value",
    onbeforeunload: "Sample value",
    onhashchange: "Sample value",
    onlanguagechange: "Sample value",
    onmessage: "Sample value",
    onmessageerror: "Sample value",
    onoffline: "Sample value",
    ononline: "Sample value",
    onpagehide: "Sample value",
    onpageshow: "Sample value",
    onpopstate: "Sample value",
    onrejectionhandled: "Sample value",
    onstorage: "Sample value",
    onunhandledrejection: "Sample value",
    onunload: "Sample value",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
  },
};
