#!/usr/bin/env php
<?php
exec('git rev-parse --abbrev-ref HEAD', $branchNameOutput, $branchNameReturnCode);
if ($branchNameReturnCode !== 0) {
    echo "Failed to get the current branch name." . PHP_EOL;
    exit(1);
}
$currentBranch = trim(implode(PHP_EOL, $branchNameOutput));

echo "Running tests on branch: $currentBranch" . PHP_EOL;
exec('./vendor/bin/simple-phpunit', $output, $returnCode);
if ($returnCode !== 0) {
  // Show full output
  echo PHP_EOL . implode(PHP_EOL, $output) . PHP_EOL;
  echo "Cannot push changes until tests pass." . PHP_EOL;
  exit(1);
}

// Show summary (last line)
echo array_pop($output) . PHP_EOL;
exit(0);