/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 9, 2025 19:18:03
 * @component Image
 * @description The img element represents an image.
 */

import React from 'react';

export interface ImgProps {
  /** CSS class names */
  className?: string;
  /** Specifies alternative text to be displayed when the image cannot be rendered. */
  alt: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  /** Specifies the decoding process applied to the image. */
  decoding?: 'async' | 'auto' | 'sync';
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  /** Specifies that an area should be part of an image map. */
  ismap?: boolean;
  lang?: string;
  /** Specifies the referrer policy for fetches initiated by the element. */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  /** Specifies the sizes of the images or icons for different display/window sizes. */
  sizes?: string;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  /** Specifies a set of image candidate URLs and descriptors for responsive images. */
  srcset?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  /** Specifies a client-side image map to be used with the element. */
  usemap?: string;
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Image - The img element represents an image.
 */
export const Img: React.FC<ImgProps> = (props: ImgProps) => {
  const {
    className,
    alt,
    ariaAtomic,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    crossorigin,
    data,
    decoding,
    dir,
    draggable,
    height,
    hidden,
    id,
    ismap,
    lang,
    referrerpolicy,
    sizes,
    src,
    srcset,
    style,
    tabindex,
    title,
    usemap,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (alt !== undefined) {
    elementProps.alt = alt;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (crossorigin !== undefined) {
    elementProps.crossorigin = crossorigin;
  }

  if (decoding !== undefined) {
    elementProps.decoding = decoding;
  }

  if (dir !== undefined) {
    elementProps.dir = dir;
  }

  if (draggable !== undefined) {
    elementProps.draggable = draggable ? true : false;
  }

  if (height !== undefined) {
    elementProps.height = height;
  }

  if (hidden !== undefined) {
    elementProps.hidden = hidden ? true : false;
  }

  if (id !== undefined) {
    elementProps.id = id;
  }

  if (ismap !== undefined) {
    elementProps.ismap = ismap ? true : false;
  }

  if (lang !== undefined) {
    elementProps.lang = lang;
  }

  if (referrerpolicy !== undefined) {
    elementProps.referrerpolicy = referrerpolicy;
  }

  if (sizes !== undefined) {
    elementProps.sizes = sizes;
  }

  if (src !== undefined) {
    elementProps.src = src;
  }

  if (srcset !== undefined) {
    elementProps.srcset = srcset;
  }

  if (style !== undefined) {
    elementProps.style = style;
  }

  if (tabindex !== undefined) {
    elementProps.tabindex = tabindex;
  }

  if (title !== undefined) {
    elementProps.title = title;
  }

  if (usemap !== undefined) {
    elementProps.usemap = usemap;
  }

  if (width !== undefined) {
    elementProps.width = width;
  }

  return React.createElement(
    'img',
    elementProps
  );
};

Img.displayName = 'Img';
