/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 4, 2025 09:31:46
 * @component Column Group
 * @description The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
 */

import React from 'react';

export interface ColgroupProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  id?: string;
  lang?: string;
  /** Specifies the number of columns the <col> element should span in a table. */
  span?: number;
  style?: React.CSSProperties;
}

/**
 * Column Group - The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
 */
export const Colgroup: React.FC<ColgroupProps> = (props: ColgroupProps) => {
  const {
    children,
    className,
    data,
    dir,
    hidden,
    id,
    lang,
    span,
    style
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (span !== undefined) {
    elementProps['span'] = span;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  return React.createElement(
    'colgroup',
    elementProps,
    children
  );
};

Colgroup.displayName = 'Colgroup';
