/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:10:33
 * @component Fieldset
 * @description The fieldset element represents a set of form controls optionally grouped under a common name.
 */

import React from 'react';

export interface FieldsetProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** The role attribute is used to define the purpose of an element. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Fieldset - The fieldset element represents a set of form controls optionally grouped under a common name.
 */
export const Fieldset: React.FC<FieldsetProps> = (props: FieldsetProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaDisabled,
    ariaHidden,
    ariaInvalid,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autocorrect,
    autofocus,
    contenteditable,
    data,
    dir,
    draggable,
    form,
    hidden,
    id,
    inputmode,
    lang,
    popover,
    role,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (popover !== undefined) {
    elementProps['popover'] = popover;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  return React.createElement(
    'fieldset',
    elementProps,
    children
  );
};

Fieldset.displayName = 'Fieldset';
