/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 20:36:46
 * @component HTML
 * @description The root element of an HTML document. It represents the top-level of the HTML structure.
 */

import React from 'react';

export interface HtmlProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  lang?: string;
  /** Specifies the address of the document's cache manifest. */
  manifest?: string;
}

/**
 * HTML - The root element of an HTML document. It represents the top-level of the HTML structure.
 */
export const Html: React.FC<HtmlProps> = (props: HtmlProps) => {
  const {
    children,
    className,
    data,
    dir,
    lang,
    manifest
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (manifest !== undefined) {
    elementProps['manifest'] = manifest;
  }

  return React.createElement(
    'html',
    elementProps,
    children
  );
};

Html.displayName = 'Html';
