/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 4, 2025 09:31:46
 * @component Inline Frame
 * @description The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */

import React from 'react';

export interface IframeProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Enables the iframe to be displayed in fullscreen mode. */
  allowfullscreen?: boolean;
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  lang?: string;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** Specifies the referrer policy for fetches initiated by the element. */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  sandbox?: string;
  /** When present, it specifies that the iframe should look like it is a part of the containing document (no borders or scrollbars). */
  seamless?: boolean;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src?: string;
  /** The value of srcdoc is a string containing HTML markup, which the browser will display as the content of the iframe. */
  srcdoc?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Inline Frame - The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */
export const Iframe: React.FC<IframeProps> = (props: IframeProps) => {
  const {
    children,
    className,
    allowfullscreen,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaHidden,
    ariaLabel,
    ariaLabelledby,
    data,
    dir,
    height,
    hidden,
    id,
    lang,
    name,
    popover,
    referrerpolicy,
    role,
    sandbox,
    seamless,
    src,
    srcdoc,
    style,
    tabindex,
    title,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (allowfullscreen !== undefined) {
    elementProps['allowfullscreen'] = allowfullscreen;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (height !== undefined) {
    elementProps['height'] = height;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (popover !== undefined) {
    elementProps['popover'] = popover;
  }

  if (referrerpolicy !== undefined) {
    elementProps['referrerpolicy'] = referrerpolicy;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (sandbox !== undefined) {
    elementProps['sandbox'] = sandbox;
  }

  if (seamless !== undefined) {
    elementProps['seamless'] = seamless;
  }

  if (src !== undefined) {
    elementProps['src'] = src;
  }

  if (srcdoc !== undefined) {
    elementProps['srcdoc'] = srcdoc;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (width !== undefined) {
    elementProps['width'] = width;
  }

  return React.createElement(
    'iframe',
    elementProps,
    children
  );
};

Iframe.displayName = 'Iframe';
