/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 20:36:46
 * @component Video
 * @description The video element is used to embed video content in a document, such as a movie clip or other video streams.
 */

import React from 'react';

export interface VideoProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  /** When present, it specifies that the audio or video will automatically start playing as soon as it can do so without stopping. */
  autoplay?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** When present, it specifies that audio or video controls should be displayed (such as play, pause, and volume). */
  controls?: boolean;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** When present, it specifies that the audio or video will start over again every time it is finished. */
  loop?: boolean;
  /** When present, it specifies that the audio output of the video should be muted. */
  muted?: boolean;
  popover?: 'auto' | 'hint' | 'manual';
  /** Specifies the URL of an image to be displayed as the video's poster (thumbnail) image. */
  poster?: string;
  preload?: 'auto' | 'metadata' | 'none';
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  spellcheck?: 'true' | 'false';
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Video - The video element is used to embed video content in a document, such as a movie clip or other video streams.
 */
export const Video: React.FC<VideoProps> = (props: VideoProps) => {
  const {
    children,
    className,
    accesskey,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaHidden,
    ariaLabelledby,
    autocapitalize,
    autofocus,
    autoplay,
    contenteditable,
    controls,
    crossorigin,
    data,
    dir,
    draggable,
    height,
    hidden,
    id,
    inputmode,
    lang,
    loop,
    muted,
    popover,
    poster,
    preload,
    role,
    spellcheck,
    src,
    style,
    tabindex,
    title,
    translate,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (autoplay !== undefined) {
    elementProps['autoplay'] = autoplay;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (controls !== undefined) {
    elementProps['controls'] = controls;
  }

  if (crossorigin !== undefined) {
    elementProps['crossorigin'] = crossorigin;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (height !== undefined) {
    elementProps['height'] = height;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (loop !== undefined) {
    elementProps['loop'] = loop;
  }

  if (muted !== undefined) {
    elementProps['muted'] = muted;
  }

  if (popover !== undefined) {
    elementProps['popover'] = popover;
  }

  if (poster !== undefined) {
    elementProps['poster'] = poster;
  }

  if (preload !== undefined) {
    elementProps['preload'] = preload;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (src !== undefined) {
    elementProps['src'] = src;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (width !== undefined) {
    elementProps['width'] = width;
  }

  return React.createElement(
    'video',
    elementProps,
    children
  );
};

Video.displayName = 'Video';
