/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 9, 2025 19:18:02
 * @component Meter
 * @description The meter element represents a scalar measurement within a known range, or a fractional value.
 */

import React from 'react';

export interface MeterProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  /** Defines the maximum value for a range input. */
  ariaValuemax?: number;
  /** Defines the minimum value for a range input. */
  ariaValuemin?: number;
  /** Specifies the current value for a range input. */
  ariaValuenow?: number;
  /** Provides a human-readable representation of the current value. */
  ariaValuetext?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  /** Specifies the high value for a range input or a meter element. */
  high?: string;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Specifies the low value for a range input. */
  low?: string;
  /** Specifies the maximum value for an input element, meter, or progress element. */
  max?: number;
  /** Specifies the minimum value for an input element or a meter element. */
  min?: string;
  /** Specifies the optimal value for a gauge or progress element. */
  optimum?: string;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the value associated with the element. The meaning and usage may vary depending on the element type. */
  value?: string;
}

/**
 * Meter - The meter element represents a scalar measurement within a known range, or a fractional value.
 */
export const Meter: React.FC<MeterProps> = (props: MeterProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    ariaValuemax,
    ariaValuemin,
    ariaValuenow,
    ariaValuetext,
    autocapitalize,
    autofocus,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    high,
    id,
    inputmode,
    lang,
    low,
    max,
    min,
    optimum,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    value
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps.accesskey = accesskey;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (ariaValuemax !== undefined) {
    elementProps['aria-valuemax'] = ariaValuemax;
  }

  if (ariaValuemin !== undefined) {
    elementProps['aria-valuemin'] = ariaValuemin;
  }

  if (ariaValuenow !== undefined) {
    elementProps['aria-valuenow'] = ariaValuenow;
  }

  if (ariaValuetext !== undefined) {
    elementProps['aria-valuetext'] = ariaValuetext;
  }

  if (autocapitalize !== undefined) {
    elementProps.autocapitalize = autocapitalize;
  }

  if (autofocus !== undefined) {
    elementProps.autofocus = autofocus ? true : false;
  }

  if (contenteditable !== undefined) {
    elementProps.contenteditable = contenteditable;
  }

  if (dir !== undefined) {
    elementProps.dir = dir;
  }

  if (draggable !== undefined) {
    elementProps.draggable = draggable ? true : false;
  }

  if (hidden !== undefined) {
    elementProps.hidden = hidden ? true : false;
  }

  if (high !== undefined) {
    elementProps.high = high;
  }

  if (id !== undefined) {
    elementProps.id = id;
  }

  if (inputmode !== undefined) {
    elementProps.inputmode = inputmode;
  }

  if (lang !== undefined) {
    elementProps.lang = lang;
  }

  if (low !== undefined) {
    elementProps.low = low;
  }

  if (max !== undefined) {
    elementProps.max = max;
  }

  if (min !== undefined) {
    elementProps.min = min;
  }

  if (optimum !== undefined) {
    elementProps.optimum = optimum;
  }

  if (slot !== undefined) {
    elementProps.slot = slot;
  }

  if (spellcheck !== undefined) {
    elementProps.spellcheck = spellcheck;
  }

  if (style !== undefined) {
    elementProps.style = style;
  }

  if (tabindex !== undefined) {
    elementProps.tabindex = tabindex;
  }

  if (title !== undefined) {
    elementProps.title = title;
  }

  if (translate !== undefined) {
    elementProps.translate = translate;
  }

  if (value !== undefined) {
    elementProps.value = value;
  }

  return React.createElement(
    'meter',
    elementProps,
    children
  );
};

Meter.displayName = 'Meter';
