/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 9, 2025 19:18:03
 * @component Anchor
 * @description The a element represents a hyperlink, linking to another resource.
 */

import React from 'react';

export interface AProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates the current item within a container or set of related elements. */
  ariaCurrent?: 'false' | 'page' | 'step' | 'location' | 'date' | 'time' | 'true';
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates whether a collapsible UI element is expanded (true) or collapsed (false). */
  ariaExpanded?: 'false' | 'true' | 'undefined';
  /** Indicates that an element has an associated popup menu, listbox, tree, grid, or dialog. */
  ariaHaspopup?: 'false' | 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates whether a toggle button is pressed (true, false, or mixed). */
  ariaPressed?: 'false' | 'true' | 'mixed' | 'undefined';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** Indicates that the linked content should be downloaded rather than displayed. */
  download?: string;
  draggable?: boolean;
  hidden?: boolean;
  /** Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used. */
  href: string;
  /** Specifies the language of the linked resource. */
  hreflang?: string;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** Specifies the relationship between the current document and the linked document. */
  rel?: 'alternate' | 'author' | 'bookmark' | 'canonical' | 'help' | 'icon' | 'license' | 'next' | 'nofollow' | 'noreferrer' | 'prefetch' | 'prev' | 'search' | 'stylesheet' | 'tag';
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'button' | 'dialog' | 'link' | 'listitem' | 'menuitem' | 'none' | 'tooltip';
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  /** Specifies where to open the linked document. */
  target?: '_blank' | '_parent' | '_self' | '_top' | string;
  /** Specifies additional information about the element, typically displayed as a tooltip. */
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the media type of the linked resource. */
  type?: string;
}

/**
 * Anchor - The a element represents a hyperlink, linking to another resource.
 */
export const A: React.FC<AProps> = (props: AProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaCurrent,
    ariaDescribedby,
    ariaDetails,
    ariaDisabled,
    ariaExpanded,
    ariaHaspopup,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaPressed,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autofocus,
    contenteditable,
    data,
    dir,
    download,
    draggable,
    hidden,
    href,
    hreflang,
    id,
    inputmode,
    lang,
    popover,
    rel,
    role,
    slot,
    spellcheck,
    style,
    tabindex,
    target,
    title,
    translate,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps.accesskey = accesskey;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaCurrent !== undefined) {
    elementProps['aria-current'] = ariaCurrent;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaExpanded !== undefined) {
    elementProps['aria-expanded'] = ariaExpanded;
  }

  if (ariaHaspopup !== undefined) {
    elementProps['aria-haspopup'] = ariaHaspopup;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaPressed !== undefined) {
    elementProps['aria-pressed'] = ariaPressed;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (autocapitalize !== undefined) {
    elementProps.autocapitalize = autocapitalize;
  }

  if (autofocus !== undefined) {
    elementProps.autofocus = autofocus ? true : false;
  }

  if (contenteditable !== undefined) {
    elementProps.contenteditable = contenteditable;
  }

  if (dir !== undefined) {
    elementProps.dir = dir;
  }

  if (download !== undefined) {
    elementProps.download = download;
  }

  if (draggable !== undefined) {
    elementProps.draggable = draggable ? true : false;
  }

  if (hidden !== undefined) {
    elementProps.hidden = hidden ? true : false;
  }

  if (href !== undefined) {
    elementProps.href = href;
  }

  if (hreflang !== undefined) {
    elementProps.hreflang = hreflang;
  }

  if (id !== undefined) {
    elementProps.id = id;
  }

  if (inputmode !== undefined) {
    elementProps.inputmode = inputmode;
  }

  if (lang !== undefined) {
    elementProps.lang = lang;
  }

  if (popover !== undefined) {
    elementProps.popover = popover;
  }

  if (rel !== undefined) {
    elementProps.rel = rel;
  }

  if (role !== undefined) {
    elementProps.role = role;
  }

  if (slot !== undefined) {
    elementProps.slot = slot;
  }

  if (spellcheck !== undefined) {
    elementProps.spellcheck = spellcheck;
  }

  if (style !== undefined) {
    elementProps.style = style;
  }

  if (tabindex !== undefined) {
    elementProps.tabindex = tabindex;
  }

  if (target !== undefined) {
    elementProps.target = target;
  }

  if (title !== undefined) {
    elementProps.title = title;
  }

  if (translate !== undefined) {
    elementProps.translate = translate;
  }

  if (type !== undefined) {
    elementProps.type = type;
  }

  return React.createElement(
    'a',
    elementProps,
    children
  );
};

A.displayName = 'A';
