/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 9, 2025 10:18:37
 * @component Html
 * @description 
 */

import React from 'react';

export interface HtmlProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  lang?: string;
  manifest?: string;
}

/**
 * Html - 
 */
export const Html: React.FC<HtmlProps> = (props: HtmlProps) => {
  const {
    children,
    className,
    data,
    dir,
    lang,
    manifest
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    elementProps[attrName] = value;
  });

  return React.createElement(
    'html',
    elementProps,
    children
  );
};

Html.displayName = 'Html';
