/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated May 18, 2026 06:38:27
 * @description Generated document using pre-made @typesafe-html5/react templates
 */

import React from 'react';
import { Details, Hr, Li, P, Summary, Ul } from '@typesafe-html5/react';

export interface AccordionExampleParams {
  node1Name?: string;
  node1Open?: string;
  content1?: string;
  content2?: string;
  node5Name?: string;
  content3?: string;
  content4?: string;
  content5?: string;
  content6?: string;
  content7?: string;
  content8?: string;
}

export const AccordionExample: React.FC<AccordionExampleParams> = (params) => {
  const defaults: Required<AccordionExampleParams> = {
    node1Name: 'example',
    node1Open: 'true',
    content1: 'Accordion 1',
    content2: 'Flamingos are known for their bright pink feathers and distinctive long necks. These birds are social creatures that live in large groups, and a group of flamingos is called a flamboyance. They can often be seen standing on one leg, which helps them conserve body heat.',
    node5Name: 'example',
    content3: 'Accordion 2',
    content4: 'Kangaroos are marsupials that are native to Australia.',
    content5: 'They are known for their powerful hind legs, which they use to hop around.',
    content6: 'Kangaroos can’t walk backwards due to the shape of their legs and tail.',
    content7: 'Baby kangaroos, called joeys, are born very small and undeveloped and must crawl into their mother’s pouch to continue developing.',
    content8: 'Some species of kangaroos can leap up to 30 feet in a single bound.',
  };
  const values = { ...defaults, ...params };
  return (
    <>
    <Details name={values.node1Name} open={values.node1Open}>
      <Summary>
        {values.content1}
      </Summary>
      <P>
        {values.content2}
      </P>
    </Details>
    <Hr />
    <Details name={values.node5Name}>
      <Summary>
        {values.content3}
      </Summary>
      <Ul>
        <Li>
          {values.content4}
        </Li>
        <Li>
          {values.content5}
        </Li>
        <Li>
          {values.content6}
        </Li>
        <Li>
          {values.content7}
        </Li>
        <Li>
          {values.content8}
        </Li>
      </Ul>
    </Details>
    </>
  );
};

AccordionExample.displayName = 'AccordionExample';
