/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated May 21, 2026 08:49:44
 * @description Generated document using pre-made @typesafe-html5/react templates
 */

import React from 'react';
import { A, Div, H3, H4, Hgroup, Img, P } from '@typesafe-html5/react';

export interface TeaserExampleParams {
  node1Class?: string;
  content1?: string;
  content2?: string;
  content3?: string;
  node6Src?: string;
  node6Alt?: string;
  node6Width?: string;
  node6Height?: string;
  node7Role?: string;
  node7Href?: string;
  content4?: string;
}

export const TeaserExample: React.FC<TeaserExampleParams> = (params) => {
  const defaults: Required<TeaserExampleParams> = {
    node1Class: 'teaser',
    content1: '{{ entry.title }}',
    content2: '{{ entry.subtitle }}',
    content3: '{{ entry.description }}',
    node6Src: '{{ entry.image.src }}',
    node6Alt: '{{ entry.image.alt }}',
    node6Width: '{{ entry.image.width }}',
    node6Height: '{{ entry.image.height }}',
    node7Role: 'button',
    node7Href: '{{ entry.button.href }}',
    content4: '{{ entry.button.text }}',
  };
  const values = { ...defaults, ...params };
  return (
    <>
    <Div className={values.node1Class}>
      <Hgroup>
        <H3>
          {values.content1}
        </H3>
        <H4>
          {values.content2}
        </H4>
      </Hgroup>
      <P>
        {values.content3}
      </P>
      <Img src={values.node6Src} alt={values.node6Alt} width={values.node6Width} height={values.node6Height} />
      <A role={values.node7Role} href={values.node7Href}>
        {values.content4}
      </A>
    </Div>
    </>
  );
};

TeaserExample.displayName = 'TeaserExample';
