/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated May 21, 2026 07:25:27
 * @description Generated document using pre-made @typesafe-html5/react templates
 */

import React from 'react';
import { A, Div, H3, H4, Hgroup, Img, P } from '@typesafe-html5/react';

export interface TeaserExampleParams {
  node1Class?: string;
  content1?: string;
  content2?: string;
  content3?: string;
  node6Src?: string;
  node6Alt?: string;
  node6Width?: string;
  node6Height?: string;
  node7Role?: string;
  node7Href?: string;
  content4?: string;
}

export const TeaserExample: React.FC<TeaserExampleParams> = (params) => {
  const defaults: Required<TeaserExampleParams> = {
    node1Class: 'teaser',
    content1: 'Headline',
    content2: 'Subheadline',
    content3: 'Description',
    node6Src: 'https://picsum.photos/340/140',
    node6Alt: 'Image description',
    node6Width: '340',
    node6Height: '140',
    node7Role: 'button',
    node7Href: '#',
    content4: 'Read more',
  };
  const values = { ...defaults, ...params };
  return (
    <>
    <Div className={values.node1Class}>
      <Hgroup>
        <H3>
          {values.content1}
        </H3>
        <H4>
          {values.content2}
        </H4>
      </Hgroup>
      <P>
        {values.content3}
      </P>
      <Img src={values.node6Src} alt={values.node6Alt} width={values.node6Width} height={values.node6Height} />
      <A role={values.node7Role} href={values.node7Href}>
        {values.content4}
      </A>
    </Div>
    </>
  );
};

TeaserExample.displayName = 'TeaserExample';
