/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:10:31
 * @component Output
 * @description The output element represents the result of a calculation or user action.
 */

import React from 'react';

export interface OutputProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  /** Refers to the <datalist> element that contains the options for an input element. */
  htmlFor?: string;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Output - The output element represents the result of a calculation or user action.
 */
export const Output: React.FC<OutputProps> = (props: OutputProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autocorrect,
    autofocus,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    htmlFor,
    id,
    inputmode,
    lang,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (htmlFor !== undefined) {
    elementProps['for'] = htmlFor;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  return React.createElement(
    'output',
    elementProps,
    children
  );
};

Output.displayName = 'Output';
