/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:10:32
 * @component Select
 * @description The select element represents a control for selecting amongst a set of options.
 */

import React from 'react';

export interface SelectProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Identifies the currently active child element (e.g., for autocomplete suggestions or composite widgets). */
  ariaActivedescendant?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** Specifies autocomplete behavior for input fields. */
  ariaAutocomplete?: 'none' | 'inline' | 'list' | 'both';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates whether a collapsible UI element is expanded (true) or collapsed (false). */
  ariaExpanded?: 'false' | 'true' | 'undefined';
  /** Indicates that an element has an associated popup menu, listbox, tree, grid, or dialog. */
  ariaHaspopup?: 'false' | 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Defines whether multiple items can be selected in a listbox, grid, or tree. */
  ariaMultiselectable?: 'false' | 'true';
  /** Specifies whether an element is horizontal or vertical. */
  ariaOrientation?: 'horizontal' | 'vertical' | 'undefined';
  /** Provides a placeholder hint for an input field. */
  ariaPlaceholder?: string;
  /** Indicates whether a toggle button is pressed (true, false, or mixed). */
  ariaPressed?: 'false' | 'true' | 'mixed' | 'undefined';
  /** Marks an input field as read-only but still selectable and focusable. */
  ariaReadonly?: 'false' | 'true';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Specifies that an input field is required before form submission. */
  ariaRequired?: 'false' | 'true';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autocomplete?: 'off' | 'on';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** When present, it specifies that an input element should be disabled. */
  disabled?: boolean;
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** When present, it specifies that the user is allowed to enter more than one value in an input element. */
  multiple?: boolean;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** When present, it specifies that an input field must be filled out before submitting the form. */
  required?: boolean;
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  /** Specifies the height of a hr element in pixels. */
  size?: number;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Select - The select element represents a control for selecting amongst a set of options.
 */
export const Select: React.FC<SelectProps> = (props: SelectProps) => {
  const {
    children,
    className,
    accesskey,
    ariaActivedescendant,
    ariaAtomic,
    ariaAutocomplete,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaDisabled,
    ariaExpanded,
    ariaHaspopup,
    ariaInvalid,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaMultiselectable,
    ariaOrientation,
    ariaPlaceholder,
    ariaPressed,
    ariaReadonly,
    ariaRelevant,
    ariaRequired,
    ariaRoledescription,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    contenteditable,
    data,
    dir,
    disabled,
    draggable,
    form,
    hidden,
    id,
    inputmode,
    lang,
    multiple,
    name,
    popover,
    required,
    role,
    size,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaActivedescendant !== undefined) {
    elementProps['aria-activedescendant'] = ariaActivedescendant;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaAutocomplete !== undefined) {
    elementProps['aria-autocomplete'] = ariaAutocomplete;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaExpanded !== undefined) {
    elementProps['aria-expanded'] = ariaExpanded;
  }

  if (ariaHaspopup !== undefined) {
    elementProps['aria-haspopup'] = ariaHaspopup;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaMultiselectable !== undefined) {
    elementProps['aria-multiselectable'] = ariaMultiselectable;
  }

  if (ariaOrientation !== undefined) {
    elementProps['aria-orientation'] = ariaOrientation;
  }

  if (ariaPlaceholder !== undefined) {
    elementProps['aria-placeholder'] = ariaPlaceholder;
  }

  if (ariaPressed !== undefined) {
    elementProps['aria-pressed'] = ariaPressed;
  }

  if (ariaReadonly !== undefined) {
    elementProps['aria-readonly'] = ariaReadonly;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRequired !== undefined) {
    elementProps['aria-required'] = ariaRequired;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocomplete !== undefined) {
    elementProps['autocomplete'] = autocomplete;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (disabled !== undefined) {
    elementProps['disabled'] = disabled;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (multiple !== undefined) {
    elementProps['multiple'] = multiple;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (popover !== undefined) {
    elementProps['popover'] = popover;
  }

  if (required !== undefined) {
    elementProps['required'] = required;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (size !== undefined) {
    elementProps['size'] = size;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  return React.createElement(
    'select',
    elementProps,
    children
  );
};

Select.displayName = 'Select';
