/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 22:54:37
 * @component Textarea
 * @description The textarea element represents a multiline plain text edit control for the element's raw value.
 */

import React from 'react';

export interface TextareaProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autocomplete?: 'off' | 'on';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  /** Specifies the visible width of a text area, in average character widths. */
  cols?: number;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** Specifies the name of the field that will contain the text direction (ltr or rtl) of the input or textarea when the form is submitted */
  dirname?: string;
  /** When present, it specifies that an input element should be disabled. */
  disabled?: boolean;
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Specifies the maximum number of characters allowed in an input field. */
  maxlength?: number;
  /** Specifies the minimum number of characters required in an input field. */
  minlength?: number;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** Specifies a short hint that describes the expected value of an input field. */
  placeholder?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** When present, it specifies that an input element is read-only. */
  readonly?: boolean;
  /** When present, it specifies that an input field must be filled out before submitting the form. */
  required?: boolean;
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  /** Specifies the visible number of lines in a text area. */
  rows?: number;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  wrap?: 'hard' | 'off' | 'soft';
}

/**
 * Textarea - The textarea element represents a multiline plain text edit control for the element's raw value.
 */
export const Textarea: React.FC<TextareaProps> = (props: TextareaProps) => {
  const {
    children,
    className,
    accesskey,
    ariaControls,
    ariaDescribedby,
    ariaDisabled,
    ariaInvalid,
    ariaLabel,
    ariaLabelledby,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    cols,
    contenteditable,
    data,
    dir,
    dirname,
    disabled,
    draggable,
    form,
    hidden,
    id,
    inputmode,
    lang,
    maxlength,
    minlength,
    name,
    placeholder,
    popover,
    readonly,
    required,
    role,
    rows,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    wrap
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocomplete !== undefined) {
    elementProps['autocomplete'] = autocomplete;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (cols !== undefined) {
    elementProps['cols'] = cols;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (dirname !== undefined) {
    elementProps['dirname'] = dirname;
  }

  if (disabled !== undefined) {
    elementProps['disabled'] = disabled;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (maxlength !== undefined) {
    elementProps['maxlength'] = maxlength;
  }

  if (minlength !== undefined) {
    elementProps['minlength'] = minlength;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (placeholder !== undefined) {
    elementProps['placeholder'] = placeholder;
  }

  if (popover !== undefined) {
    elementProps['popover'] = popover;
  }

  if (readonly !== undefined) {
    elementProps['readonly'] = readonly;
  }

  if (required !== undefined) {
    elementProps['required'] = required;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (rows !== undefined) {
    elementProps['rows'] = rows;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (wrap !== undefined) {
    elementProps['wrap'] = wrap;
  }

  return React.createElement(
    'textarea',
    elementProps,
    children
  );
};

Textarea.displayName = 'Textarea';
