/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 22:54:41
 * @component Break
 * @description The br element represents a line break.
 */

import React from 'react';

export interface BrProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  id?: string;
  style?: React.CSSProperties;
}

/**
 * Break - The br element represents a line break.
 */
export const Br: React.FC<BrProps> = (props: BrProps) => {
  const {
    className,
    data,
    dir,
    hidden,
    id,
    style
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  return React.createElement(
    'br',
    elementProps
  );
};

Br.displayName = 'Br';
