/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 30, 2025 10:28
 * @component Option
 * @description The option element represents an item in a select dropdown list.
 */

export default {
  title: "HTML5/Block Elements/Option",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The option element represents an item in a select dropdown list.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaBusy: {
      type: {
        name: "string",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLevel: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the hierarchical level of an element (e.g., headings, tree items).",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaPosinset: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines an element\'s position within a set (1-based index).",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaSelected: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether an item is selected (e.g., in a list, table, or tree).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "undefined"],
    },
    ariaSetsize: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the total number of items in a set.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    label: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a label for the associated form control, option group, or option.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    selected: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an option should be pre-selected when the page loads.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    slot: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: (args) => {
    let el = document.createElement("option");
    el.innerHTML = args.text;

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaAtomic: "",
    ariaBusy: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaDetails: "Sample value",
    ariaHidden: "",
    ariaKeyshortcuts: "Sample value",
    ariaLabelledby: "Sample value",
    ariaLevel: 0,
    ariaLive: "",
    ariaPosinset: 0,
    ariaRelevant: "",
    ariaRoledescription: "Sample value",
    ariaSelected: "",
    ariaSetsize: 0,
    autocapitalize: "",
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    disabled: false,
    draggable: false,
    hidden: false,
    id: "Sample value",
    inputmode: "",
    label: "Sample value",
    lang: "Sample value",
    popover: "",
    role: "",
    selected: false,
    slot: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    value: "Sample value",
  },
};
