/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 4, 2025 09:34:07
 * @component Details - Composed Example
 * @description The details element represents a disclosure widget from which the user can obtain additional information or controls.
 *
 * CONTENT MODEL:
 * - Can be a child of: Aside, Body, DefinitionDescription, Dialog, Division, Footer, Form, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: Division, DefinitionList, Form, ListItem, OrderedList, Paragraph, PreformattedText, Summary, Table, UnorderedList
 */

import * as PStories from '../block/p.stories.js';
import * as SummaryStories from '../block/summary.stories.js';

export default {
  title: "HTML5/Block Elements/Details - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The details element represents a disclosure widget from which the user can obtain additional information or controls.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Details with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('details');
    parent.className = 'example';

    const child0 = PStories.Default.render(PStories.Default.args);
    parent.appendChild(child0);
    const child1 = PStories.Default.render(PStories.Default.args);
    parent.appendChild(child1);
    const child2 = SummaryStories.Default.render(SummaryStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
