/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 4, 2025 09:34:07
 * @component Head - Composed Example
 * @description The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 *
 * CONTENT MODEL:
 * - Can be a child of: HTML
 * - Can contain: Base, Link, Meta, NoScript, Script, Style, Title
 * - UNIQUE PER PARENT: Only one allowed per parent element
 */

import * as BaseStories from '../void/base.stories.js';
import * as LinkStories from '../void/link.stories.js';
import * as MetaStories from '../void/meta.stories.js';
import * as ScriptStories from '../void/script.stories.js';

export default {
  title: "HTML5/Void Elements/Head - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Head with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('head');
    parent.className = 'example';

    const child0 = BaseStories.Default.render(BaseStories.Default.args);
    parent.appendChild(child0);
    const child1 = LinkStories.Default.render(LinkStories.Default.args);
    parent.appendChild(child1);
    const child2 = LinkStories.Default.render(LinkStories.Default.args);
    parent.appendChild(child2);
    const child3 = MetaStories.Default.render(MetaStories.Default.args);
    parent.appendChild(child3);
    const child4 = MetaStories.Default.render(MetaStories.Default.args);
    parent.appendChild(child4);
    const child5 = ScriptStories.Default.render(ScriptStories.Default.args);
    parent.appendChild(child5);

    return parent;
  },
};
