/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:11:00
 * @component HTML - Composed Example
 * @description The root element of an HTML document. It represents the top-level of the HTML structure.
 *
 * CONTENT MODEL:
 * - Can contain: Body, Head
 * - UNIQUE: Only one allowed per document
 * - UNIQUE PER PARENT: Only one allowed per parent element
 */

import * as BodyStories from '../block/body.stories.js';
import * as HeadStories from '../void/head.stories.js';

export default {
  title: "HTML5/Block Elements/HTML - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The root element of an HTML document. It represents the top-level of the HTML structure.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing HTML with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('html');
    parent.className = 'example';

    const child0 = BodyStories.Default.render(BodyStories.Default.args);
    parent.appendChild(child0);
    const child1 = HeadStories.Default.render(HeadStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
