/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 4, 2025 09:34:06
 * @component Select - Composed Example
 * @description The select element represents a control for selecting amongst a set of options.
 *
 * CONTENT MODEL:
 * - Can be a child of: Aside, Body, DefinitionDescription, Dialog, Division, Fieldset, Footer, Form, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: OptionGroup, Option
 */

import * as OptgroupStories from '../block/optgroup.stories.js';
import * as OptionStories from '../block/option.stories.js';

export default {
  title: "HTML5/Inline Elements/Select - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The select element represents a control for selecting amongst a set of options.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Select with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('select');
    parent.className = 'example';

    const child0 = OptgroupStories.Default.render(OptgroupStories.Default.args);
    parent.appendChild(child0);
    const child1 = OptgroupStories.Default.render(OptgroupStories.Default.args);
    parent.appendChild(child1);
    const child2 = OptionStories.Default.render(OptionStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
