/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 5, 2025 12:00
 * @component Inline Frame
 * @description The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */

export default {
  title: "HTML5/Block Elements/Inline Frame",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    allowfullscreen: {
      type: {
        name: "boolean",
        required: false
      },
      description: "Enables the iframe to be displayed in fullscreen mode.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    ariaBusy: {
      type: {
        name: "string",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaLabel: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    referrerpolicy: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    sandbox: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    seamless: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the iframe should look like it is a part of the containing document (no borders or scrollbars).",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    src: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    srcdoc: {
      type: {
        name: "string",
        required: false
      },
      description: "The value of srcdoc is a string containing HTML markup, which the browser will display as the content of the iframe.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    allowfullscreen,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaHidden,
    ariaLabel,
    ariaLabelledby,
    classProp,
    data,
    dir,
    height,
    hidden,
    id,
    lang,
    name,
    popover,
    referrerpolicy,
    role,
    sandbox,
    seamless,
    src,
    srcdoc,
    style,
    tabindex,
    title,
    width,
  }) => {
    let el = document.createElement("iframe");
    el.innerHTML = text;
    if (allowfullscreen) {
      el.setAttribute('allowfullscreen', allowfullscreen);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (popover) {
      el.setAttribute('popover', popover);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (sandbox) {
      el.setAttribute('sandbox', sandbox);
    }
    if (seamless) {
      el.setAttribute('seamless', seamless);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (srcdoc) {
      el.setAttribute('srcdoc', srcdoc);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    allowfullscreen: false,
    ariaBusy: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaHidden: "",
    ariaLabel: "Sample value",
    ariaLabelledby: "Sample value",
    classProp: "Sample value",
    data: {},
    dir: "",
    height: "Sample value",
    hidden: false,
    id: "Sample value",
    lang: "Sample value",
    name: "Sample value",
    popover: "",
    referrerpolicy: "",
    role: "",
    sandbox: "Sample value",
    seamless: false,
    src: "Sample value",
    srcdoc: "Sample value",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    width: "Sample value",
  },
};
