/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 30, 2025 17:26:54
 * @component Wbr
 * @description 
 */

export interface WbrProps {
  /**
   * Represents Alpine.js attributes on the element
   */
  'alpine-attributes'?: string | null | undefined;
  /**
   * Represents the text direction of the element
   */
  dir?: 'ltr' | 'rtl' | 'auto' | null | undefined;
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
}

/**
 * Wbr - 
 */
export class Wbr {
  private element: HTMLElement;

  constructor(props: WbrProps = {}) {
    this.element = document.createElement('wbr');
    this.applyProps(props);
  }

  private applyProps(props: WbrProps): void {
    if (props['alpine-attributes'] !== undefined) {
      this.element.setAttribute('alpine-attributes', String(props['alpine-attributes']));
    }
    if (props.dir !== undefined) {
      this.setDir(props.dir);
    }
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
  }

  setAlpineAttributes(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('alpine-attributes');
    } else {
      this.element.setAttribute('alpine-attributes', String(value));
    }
    return this;
  }

  setDir(value: 'ltr' | 'rtl' | 'auto' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('dir');
    } else {
      this.element.setAttribute('dir', String(value));
    }
    return this;
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
