/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 30, 2025 10:28
 * @component Anchor
 * @description The a element represents a hyperlink, linking to another resource.
 */

export default {
  title: "HTML5/Inline Elements/Anchor",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The a element represents a hyperlink, linking to another resource.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaBusy: {
      type: {
        name: "string",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaCurrent: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates the current item within a container or set of related elements.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "page", "step", "location", "date", "time", "true"],
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDisabled: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaExpanded: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether a collapsible UI element is expanded (true) or collapsed (false).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "undefined"],
    },
    ariaHaspopup: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that an element has an associated popup menu, listbox, tree, grid, or dialog.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "menu", "listbox", "tree", "grid", "dialog"],
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabel: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaPressed: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether a toggle button is pressed (true, false, or mixed).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "mixed", "undefined"],
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    download: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the linked content should be downloaded rather than displayed.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    href: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hreflang: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the language of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    rel: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the relationship between the current document and the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alternate", "author", "bookmark", "canonical", "help", "icon", "license", "next", "nofollow", "noreferrer", "prefetch", "prev", "search", "stylesheet", "tag"],
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "button", "dialog", "link", "listitem", "menuitem", "none", "tooltip"],
    },
    slot: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    target: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies where to open the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "_blank", "_parent", "_self", "_top"],
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: (args) => {
    let el = document.createElement("a");
    el.innerHTML = args.text;

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaAtomic: "",
    ariaBusy: "",
    ariaControls: "Sample value",
    ariaCurrent: "",
    ariaDescribedby: "Sample value",
    ariaDetails: "Sample value",
    ariaDisabled: "",
    ariaExpanded: "",
    ariaHaspopup: "",
    ariaKeyshortcuts: "Sample value",
    ariaLabel: "Sample value",
    ariaLabelledby: "Sample value",
    ariaLive: "",
    ariaPressed: "",
    ariaRelevant: "",
    ariaRoledescription: "Sample value",
    autocapitalize: "",
    autofocus: false,
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    download: "Sample value",
    draggable: false,
    hidden: false,
    href: "Sample value",
    hreflang: "Sample value",
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    popover: "",
    rel: "",
    role: "",
    slot: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    target: "",
    title: "Sample value",
    translate: "",
    type: "Sample value",
  },
};
