/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 9, 2025 10:18:37
 * @component Track
 * @description 
 */

import React from 'react';

export interface TrackProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  hidden?: boolean;
  htmlDefault?: boolean;
  id?: string;
  kind?: 'captions' | 'chapters' | 'descriptions' | 'metadata' | 'subtitles';
  label?: string;
  lang?: string;
  src?: string;
  srclang?: string;
  style?: React.CSSProperties;
}

/**
 * Track - 
 */
export const Track: React.FC<TrackProps> = (props: TrackProps) => {
  const {
    className,
    data,
    hidden,
    htmlDefault,
    id,
    kind,
    label,
    lang,
    src,
    srclang,
    style
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'hidden' || key === 'htmlDefault')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'track',
    elementProps
  );
};

Track.displayName = 'Track';
