/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 9, 2025 19:18:07
 * @component Word Break Opportunity
 * @description The wbr element represents a word break opportunity.
 */

import React from 'react';

export interface WbrProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  id?: string;
}

/**
 * Word Break Opportunity - The wbr element represents a word break opportunity.
 */
export const Wbr: React.FC<WbrProps> = (props: WbrProps) => {
  const {
    className,
    data,
    dir,
    hidden,
    id
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (dir !== undefined) {
    elementProps.dir = dir;
  }

  if (hidden !== undefined) {
    elementProps.hidden = hidden ? true : false;
  }

  if (id !== undefined) {
    elementProps.id = id;
  }

  return React.createElement(
    'wbr',
    elementProps
  );
};

Wbr.displayName = 'Wbr';
