/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 01:31
 * @component Column
 * @description The col element represents a column in a table.
 */

import {
  withActions
} from '@storybook/addon-actions/decorator';

export default {
  title: "HTML5/Void Elements/Column",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The col element represents a column in a table.",
      },
    },
  },
  argTypes: {
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    span: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the number of columns the <col> element should span in a table.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    classProp,
    data,
    id,
    style,
    span,
    width,
    style,
  }) => {
    let el = document.createElement("col");
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (span) {
      el.setAttribute('span', span);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    return el;
  },
  decorators: [withActions],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    classProp: "Sample value",
    data: {},
    id: "Sample value",
    style: "Sample value",
    span: "Sample value",
    width: "Sample value",
  },
};
