/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 01:31
 * @component Parameter
 * @description The param element defines parameters for an object element.
 */

import {
  withActions
} from '@storybook/addon-actions/decorator';

export default {
  title: "HTML5/Void Elements/Parameter",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The param element defines parameters for an object element.",
      },
    },
  },
  argTypes: {
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    hidden: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
  },
  render: ({
    classProp,
    data,
    hidden,
    id,
    style,
    name,
    value,
    style,
    hidden,
  }) => {
    let el = document.createElement("param");
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    return el;
  },
  decorators: [withActions],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    classProp: "Sample value",
    data: {},
    hidden: false,
    id: "Sample value",
    style: "Sample value",
    name: "Sample value",
    value: "Sample value",
  },
};
