/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 16:17
 * @component Scalable Vector Graphics
 * @description The svg element is a container for embedded SVG graphics.
 */

import {
  withActions
} from '@storybook/addon-actions/decorator';

export default {
  title: "HTML5/Inline Elements/Scalable Vector Graphics",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The svg element is a container for embedded SVG graphics.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaBusy: {
      type: {
        name: "enum",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaLabel: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    fill: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the color of the interior of shapes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    stroke: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the color of the stroke (outline) of shapes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    viewBox: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the position and dimension, in user space, of an SVG viewport.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    xmlns: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the XML namespace for the SVG element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    accesskey,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaHidden,
    ariaLabel,
    ariaLabelledby,
    autocapitalize,
    autofocus,
    classProp,
    contenteditable,
    data,
    dir,
    draggable,
    fill,
    height,
    hidden,
    id,
    inputmode,
    lang,
    popover,
    role,
    spellcheck,
    stroke,
    style,
    tabindex,
    title,
    translate,
    viewBox,
    width,
    xmlns,
  }) => {
    let el = document.createElement("svg");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (fill) {
      el.setAttribute('fill', fill);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (popover) {
      el.setAttribute('popover', popover);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (stroke) {
      el.setAttribute('stroke', stroke);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (viewBox) {
      el.setAttribute('view-box', viewBox);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (xmlns) {
      el.setAttribute('xmlns', xmlns);
    }
    return el;
  },
  decorators: [withActions],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaBusy: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaHidden: "",
    ariaLabel: "Sample value",
    ariaLabelledby: "Sample value",
    autocapitalize: "",
    autofocus: false,
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    draggable: false,
    fill: "Sample value",
    height: "Sample value",
    hidden: false,
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    popover: false,
    role: "",
    spellcheck: "",
    stroke: "Sample value",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    viewBox: "Sample value",
    width: "Sample value",
    xmlns: "Sample value",
  },
};
