/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 17:53
 * @component Textarea
 * @description The textarea element represents a multiline plain text edit control for the element's raw value.
 */

import {
  withActions
} from '@storybook/addon-actions/decorator';

export default {
  title: "HTML5/Inline Elements/Textarea",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The textarea element represents a multiline plain text edit control for the element\'s raw value.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDisabled: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaInvalid: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the value entered does not conform to the expected format.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "grammar", "spelling"],
    },
    ariaLabel: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autocomplete: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autocorrect: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    cols: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the visible width of a text area, in average character widths.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    dirname: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name of the field that will contain the text direction (ltr or rtl) of the input or textarea when the form is submitted",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    form: {
      type: {
        name: "string",
        required: false
      },
      description: "Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    maxlength: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the maximum number of characters allowed in an input field.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    minlength: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the minimum number of characters required in an input field.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    placeholder: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a short hint that describes the expected value of an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    readonly: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element is read-only.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    required: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input field must be filled out before submitting the form.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    rows: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the visible number of lines in a text area.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    wrap: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "hard", "off", "soft"],
    },
  },
  render: ({
    text,
    accesskey,
    ariaControls,
    ariaDescribedby,
    ariaDisabled,
    ariaInvalid,
    ariaLabel,
    ariaLabelledby,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    classProp,
    cols,
    contenteditable,
    data,
    dir,
    dirname,
    disabled,
    draggable,
    form,
    hidden,
    id,
    inputmode,
    lang,
    maxlength,
    minlength,
    name,
    placeholder,
    popover,
    readonly,
    required,
    role,
    rows,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    wrap,
  }) => {
    let el = document.createElement("textarea");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaDisabled) {
      el.setAttribute('aria-disabled', ariaDisabled);
    }
    if (ariaInvalid) {
      el.setAttribute('aria-invalid', ariaInvalid);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autocomplete) {
      el.setAttribute('autocomplete', autocomplete);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (cols) {
      el.setAttribute('cols', cols);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (dirname) {
      el.setAttribute('dirname', dirname);
    }
    if (disabled) {
      el.setAttribute('disabled', disabled);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (form) {
      el.setAttribute('form', form);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (maxlength) {
      el.setAttribute('maxlength', maxlength);
    }
    if (minlength) {
      el.setAttribute('minlength', minlength);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (placeholder) {
      el.setAttribute('placeholder', placeholder);
    }
    if (popover) {
      el.setAttribute('popover', popover);
    }
    if (readonly) {
      el.setAttribute('readonly', readonly);
    }
    if (required) {
      el.setAttribute('required', required);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (rows) {
      el.setAttribute('rows', rows);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (wrap) {
      el.setAttribute('wrap', wrap);
    }
    return el;
  },
  decorators: [withActions],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaDisabled: "",
    ariaInvalid: "",
    ariaLabel: "Sample value",
    ariaLabelledby: "Sample value",
    autocapitalize: "",
    autocomplete: "",
    autocorrect: "",
    autofocus: false,
    classProp: "Sample value",
    cols: 0,
    contenteditable: "",
    data: {},
    dir: "",
    dirname: "Sample value",
    disabled: false,
    draggable: false,
    form: "Sample value",
    hidden: false,
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    maxlength: 0,
    minlength: 0,
    name: "Sample value",
    placeholder: "Sample value",
    popover: "",
    readonly: false,
    required: false,
    role: "",
    rows: 0,
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    wrap: "",
  },
};
