/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 9, 2025 10:18:37
 * @component Audio
 * @description 
 */

import React from 'react';

export interface AudioProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  ariaAtomic?: 'false' | 'true';
  ariaBusy?: 'true' | 'false';
  ariaControls?: string;
  ariaDescribedby?: string;
  ariaDetails?: string;
  ariaKeyshortcuts?: string;
  ariaLabelledby?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRoledescription?: string;
  autoplay?: boolean;
  controls?: boolean;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  lang?: string;
  loop?: boolean;
  muted?: boolean;
  popover?: 'auto' | 'hint' | 'manual';
  preload?: 'auto' | 'metadata' | 'none';
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  slot?: string;
  src?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Audio - 
 */
export const Audio: React.FC<AudioProps> = (props: AudioProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autoplay,
    controls,
    crossorigin,
    data,
    draggable,
    hidden,
    id,
    lang,
    loop,
    muted,
    popover,
    preload,
    role,
    slot,
    src,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autoplay' || key === 'controls' || key === 'draggable' || key === 'hidden' || key === 'loop' || key === 'muted')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'audio',
    elementProps,
    children
  );
};

Audio.displayName = 'Audio';
