/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 9, 2025 19:18:07
 * @component Audio
 * @description The audio element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the source element.
 */

import React from 'react';

export interface AudioProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  /** When present, it specifies that the audio or video will automatically start playing as soon as it can do so without stopping. */
  autoplay?: boolean;
  /** When present, it specifies that audio or video controls should be displayed (such as play, pause, and volume). */
  controls?: boolean;
  /** Specifies how the element handles cross-origin requests. */
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  lang?: string;
  /** When present, it specifies that the audio or video will start over again every time it is finished. */
  loop?: boolean;
  /** When present, it specifies that the audio output of the video should be muted. */
  muted?: boolean;
  popover?: 'auto' | 'hint' | 'manual';
  preload?: 'auto' | 'metadata' | 'none';
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  slot?: string;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Audio - The audio element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the source element.
 */
export const Audio: React.FC<AudioProps> = (props: AudioProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autoplay,
    controls,
    crossorigin,
    data,
    draggable,
    hidden,
    id,
    lang,
    loop,
    muted,
    popover,
    preload,
    role,
    slot,
    src,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps.accesskey = accesskey;
  }

  if (ariaAtomic !== undefined) {
    elementProps['aria-atomic'] = ariaAtomic;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDescribedby !== undefined) {
    elementProps['aria-describedby'] = ariaDescribedby;
  }

  if (ariaDetails !== undefined) {
    elementProps['aria-details'] = ariaDetails;
  }

  if (ariaKeyshortcuts !== undefined) {
    elementProps['aria-keyshortcuts'] = ariaKeyshortcuts;
  }

  if (ariaLabelledby !== undefined) {
    elementProps['aria-labelledby'] = ariaLabelledby;
  }

  if (ariaLive !== undefined) {
    elementProps['aria-live'] = ariaLive;
  }

  if (ariaRelevant !== undefined) {
    elementProps['aria-relevant'] = ariaRelevant;
  }

  if (ariaRoledescription !== undefined) {
    elementProps['aria-roledescription'] = ariaRoledescription;
  }

  if (autoplay !== undefined) {
    elementProps.autoplay = autoplay ? true : false;
  }

  if (controls !== undefined) {
    elementProps.controls = controls ? true : false;
  }

  if (crossorigin !== undefined) {
    elementProps.crossorigin = crossorigin;
  }

  if (draggable !== undefined) {
    elementProps.draggable = draggable ? true : false;
  }

  if (hidden !== undefined) {
    elementProps.hidden = hidden ? true : false;
  }

  if (id !== undefined) {
    elementProps.id = id;
  }

  if (lang !== undefined) {
    elementProps.lang = lang;
  }

  if (loop !== undefined) {
    elementProps.loop = loop ? true : false;
  }

  if (muted !== undefined) {
    elementProps.muted = muted ? true : false;
  }

  if (popover !== undefined) {
    elementProps.popover = popover;
  }

  if (preload !== undefined) {
    elementProps.preload = preload;
  }

  if (role !== undefined) {
    elementProps.role = role;
  }

  if (slot !== undefined) {
    elementProps.slot = slot;
  }

  if (src !== undefined) {
    elementProps.src = src;
  }

  if (style !== undefined) {
    elementProps.style = style;
  }

  if (tabindex !== undefined) {
    elementProps.tabindex = tabindex;
  }

  if (title !== undefined) {
    elementProps.title = title;
  }

  if (translate !== undefined) {
    elementProps.translate = translate;
  }

  return React.createElement(
    'audio',
    elementProps,
    children
  );
};

Audio.displayName = 'Audio';
